set(APPLICATION_DESCRIPTION "Nuvv Empresas - Comunicador Corporativo")
set(APPLICATION_ID "br.com.nuvv.empresas")
set(APPLICATION_NAME "Nuvv Connect")
set(APPLICATION_URL "https://www.nuvv.com.br/empresarial")
set(APPLICATION_VENDOR "Nuvv Telecom")
set(APPLICATION_LICENCE "GNU General Public License V3")
set(APPLICATION_LICENCE_URL "https://www.gnu.org/licenses/gpl-3.0.html")
set(APPLICATION_START_LICENCE "2026")

set(EXECUTABLE_NAME nuvv)
